(** LLVM IR code generation for Lumiere.
    Emits LLVM IR as text using GMP for arbitrary precision integers. *)

open Ast

type env = {
  vars : (string * string) list;  (* name -> llvm register (ptr to mpz_t) *)
  counter : int;                  (* for fresh temporaries *)
  strings : (string * string) list; (* string constant name -> value *)
}

let fresh (env : env) (prefix : string) : string * env =
  let (reg : string) = Printf.sprintf "%%%s%d" prefix env.counter in
  (reg, { env with counter = env.counter + 1 })

let add_string (env : env) (value : string) : string * env =
  let (name : string) = Printf.sprintf "@.str%d" (List.length env.strings) in
  (name, { env with strings = (name, value) :: env.strings })

let emit (buf : Buffer.t) (fmt : ('a, Buffer.t, unit) format) : 'a =
  Printf.bprintf buf fmt

let rec codegen_expr (buf : Buffer.t) (env : env) (expr : expr) : string * env =
  match expr with
  | IntLit s ->
    let ((reg, env) : string * env) = fresh env "t" in
    let ((str_name, env) : string * env) = add_string env s in
    emit buf "  %s = alloca [16 x i8], align 8\n" reg;
    emit buf "  call void @__gmpz_init_set_str(ptr %s, ptr %s, i32 10)\n" reg str_name;
    (reg, env)
  | Var name ->
    (match List.assoc_opt name env.vars with
     | Some reg -> (reg, env)
     | None -> failwith (Printf.sprintf "Undefined variable: %s" name))
  | BinOp (op, lhs, rhs) ->
    let ((lreg, env) : string * env) = codegen_expr buf env lhs in
    let ((rreg, env) : string * env) = codegen_expr buf env rhs in
    let ((res, env) : string * env) = fresh env "t" in
    emit buf "  %s = alloca [16 x i8], align 8\n" res;
    emit buf "  call void @__gmpz_init(ptr %s)\n" res;
    let (fn : string) = match op with
      | Add -> "__gmpz_add"
      | Sub -> "__gmpz_sub"
      | Mul -> "__gmpz_mul"
    in
    emit buf "  call void @%s(ptr %s, ptr %s, ptr %s)\n" fn res lreg rreg;
    (res, env)

let codegen_stmt (buf : Buffer.t) (env : env) (stmt : stmt) : env =
  match stmt with
  | Let (name, expr) ->
    let ((reg, env) : string * env) = codegen_expr buf env expr in
    { env with vars = (name, reg) :: env.vars }
  | Print expr ->
    let ((reg, env) : string * env) = codegen_expr buf env expr in
    emit buf "  call i32 (ptr, ...) @__gmp_printf(ptr @.fmt, ptr %s)\n" reg;
    env

let codegen (prog : program) : string =
  let (buf : Buffer.t) = Buffer.create 1024 in
  let (env : env) = { vars = []; counter = 0; strings = [] } in
  (* Generate body into a temporary buffer so we collect string constants *)
  let (body_buf : Buffer.t) = Buffer.create 1024 in
  let (env : env) = List.fold_left (codegen_stmt body_buf) env prog in
  (* Emit header with collected string constants *)
  emit buf "; Generated by Lumiere compiler\n\n";
  List.iter (fun ((name, value) : string * string) ->
    let (len : int) = String.length value + 1 in
    emit buf "%s = private unnamed_addr constant [%d x i8] c\"%s\\00\"\n" name len value
  ) (List.rev env.strings);
  emit buf "@.fmt = private unnamed_addr constant [5 x i8] c\"%%Zd\\0A\\00\"\n\n";
  emit buf "declare void @__gmpz_init(ptr)\n";
  emit buf "declare i32 @__gmpz_init_set_str(ptr, ptr, i32)\n";
  emit buf "declare void @__gmpz_add(ptr, ptr, ptr)\n";
  emit buf "declare void @__gmpz_sub(ptr, ptr, ptr)\n";
  emit buf "declare void @__gmpz_mul(ptr, ptr, ptr)\n";
  emit buf "declare i32 @__gmp_printf(ptr, ...)\n\n";
  emit buf "define i32 @main() {\n";
  emit buf "entry:\n";
  Buffer.add_buffer buf body_buf;
  emit buf "  ret i32 0\n";
  emit buf "}\n";
  Buffer.contents buf
